# This is an example parameter file for the AMST workflow
# Copy this parameter file to your desired location and adjust to your needs
# Then run the workflow using:
#    amst2-wf-amst-run /path/to/my/params-amst-bspline-local.yaml

general:
  # These three can be omitted if AMST is run inside the same target folder as the pre-align >>>
  input_dirpath: /path_to_your_input # Defaults to <output_dirpath>/stack_to_ome_zarr/input-raw.ome.zarr
  pre_align_dirpath: 
    /path_results_prealign/apply_pre_align/nsbs-pre-align.ome.zarr # Defaults to <output_dirpath>/apply_pre_align/nsbs-pre-align.ome.zarr
  pre_align_transforms: /path_results_prealign/nsbs-pre-align.json # Defaults to <output_dirpath>/nsbs-pre-align.json
  # <<<run
  output_dirpath: /path_to_your_output/test_amst2
  stack_key: s0
  stack_pattern: '*.tif'
  cores: 12
  batch_size: 8
  max_cores_per_task: 8

amst:
  elastix_parameter_file: auto
  transform: bspline
  median_radius: 7
  gaussian_sigma: 2.0
  auto_mask_off: false

apply_amst: {}

amst_to_tif_stack:
  active: true
